name: falcon
description: Falcon - Secure Military Messaging App with VPN and TOTP Authentication
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.1.1
  
  # Networking
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  dio: ^5.3.2
  
  # Security & Encryption
  flutter_secure_storage: ^9.0.0
  cryptography: ^2.5.0
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  local_auth: ^2.1.7
  
  # Database
  sqflite: ^2.3.0
  sqflite_sqlcipher: ^3.0.0
  path_provider: ^2.1.1
  path: ^1.8.3
  
  # QR Code & TOTP
  qr_flutter: ^4.1.0
  otp: ^3.1.4
  base32: ^2.1.3
  
  # File Handling
  file_picker: ^8.0.0+1
  image_picker: ^1.0.7
  mime: ^1.0.4
  
  # UI & Animations
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0
  flutter_staggered_animations: ^1.1.1
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.1.0
  logger: ^2.0.2+1
  permission_handler: ^11.0.1
  device_info_plus: ^9.1.0
  socket_io_client: ^3.0.2
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.2.1
  firebase_messaging: ^15.1.3
  
  # Error Reporting
  sentry_flutter: ^8.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1

  # Launcher Icons should be here (not in dependencies!)
  flutter_launcher_icons: ^0.13.1

# Flutter Launcher Icons configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  adaptive_icon_background: "#1a237e"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/